version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/urswat
      - SENDGRID_API_KEY=your_sendgrid_api_key
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urswat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

